// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StackFlow.Infrastructure.Persistence;

#nullable disable

namespace StackFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329163132_202603_InitialCreate")]
    partial class _202603_InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StackFlow.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StackFlow.Domain.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Workflows", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "HR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard onboarding process for new employees.",
                            IsActive = true,
                            Name = "Employee Onboarding",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkspaceId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "Finance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Approval workflow for purchase requests.",
                            IsActive = true,
                            Name = "Purchase Approval",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkspaceId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "Operations",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Structured process for offboarding departing clients.",
                            IsActive = true,
                            Name = "Client Offboarding",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WorkspaceId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStateId");

                    b.ToTable("WorkflowAudits", (string)null);
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContextType")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkflowStates", (string)null);
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionConfig")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DefaultAssignedToEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DueAtOffsetDays")
                        .HasColumnType("integer");

                    b.Property<int>("NodeType")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowTasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AssigneeType = 0,
                            Description = "Prepare and send the signed offer letter to the new employee.",
                            DueAtOffsetDays = 1,
                            NodeType = 0,
                            OrderIndex = 0,
                            Title = "Send offer letter",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AssigneeType = 0,
                            Description = "Provision laptop, accounts, and access credentials for the new starter.",
                            DueAtOffsetDays = 3,
                            NodeType = 0,
                            OrderIndex = 1,
                            Title = "Set up workstation",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AssigneeType = 0,
                            Description = "Book the orientation session and send calendar invites.",
                            DueAtOffsetDays = 3,
                            NodeType = 0,
                            OrderIndex = 2,
                            Title = "Schedule orientation session",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            AssigneeType = 0,
                            Description = "Ensure all employment forms, tax declarations, and NDAs are signed.",
                            DueAtOffsetDays = 5,
                            NodeType = 0,
                            OrderIndex = 3,
                            Title = "Complete HR paperwork",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            AssigneeType = 0,
                            Description = "Pair the new employee with an experienced team member.",
                            DueAtOffsetDays = 5,
                            NodeType = 0,
                            OrderIndex = 4,
                            Title = "Assign buddy / mentor",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            AssigneeType = 0,
                            Description = "Schedule and conduct a 30-day review meeting with the new starter.",
                            DueAtOffsetDays = 30,
                            NodeType = 0,
                            OrderIndex = 5,
                            Title = "30-day check-in",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            AssigneeType = 0,
                            Description = "Complete the purchase request form with vendor details, cost, and business justification.",
                            DueAtOffsetDays = 1,
                            NodeType = 0,
                            OrderIndex = 0,
                            Title = "Submit purchase request",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            AssigneeType = 0,
                            Description = "Line manager reviews and approves or declines the purchase request.",
                            DueAtOffsetDays = 3,
                            NodeType = 1,
                            OrderIndex = 1,
                            Title = "Manager approval",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            AssigneeType = 0,
                            Description = "Finance team raises and issues the purchase order to the vendor.",
                            DueAtOffsetDays = 5,
                            NodeType = 0,
                            OrderIndex = 2,
                            Title = "Raise purchase order",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            AssigneeType = 0,
                            Description = "Verify goods or services received and mark the purchase order as complete.",
                            DueAtOffsetDays = 14,
                            NodeType = 0,
                            OrderIndex = 3,
                            Title = "Confirm delivery and close",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            AssigneeType = 0,
                            Description = "Notify relevant internal teams of the client's departure date.",
                            DueAtOffsetDays = 1,
                            NodeType = 0,
                            OrderIndex = 0,
                            Title = "Send offboarding notification",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            AssigneeType = 0,
                            Description = "Collect any company equipment, access credentials, or materials from the client.",
                            DueAtOffsetDays = 3,
                            NodeType = 0,
                            OrderIndex = 1,
                            Title = "Retrieve client assets",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            AssigneeType = 0,
                            Description = "Remove client access from all internal systems and shared resources.",
                            DueAtOffsetDays = 3,
                            NodeType = 0,
                            OrderIndex = 2,
                            Title = "Revoke system access",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            AssigneeType = 0,
                            Description = "Generate and send the final invoice for any outstanding services.",
                            DueAtOffsetDays = 5,
                            NodeType = 0,
                            OrderIndex = 3,
                            Title = "Issue final invoice",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            AssigneeType = 0,
                            Description = "Schedule and conduct an exit interview to capture feedback.",
                            DueAtOffsetDays = 7,
                            NodeType = 0,
                            OrderIndex = 4,
                            Title = "Conduct exit interview",
                            WorkflowId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTaskAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowTaskStateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTaskStateId");

                    b.ToTable("WorkflowTaskAudits", (string)null);
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTaskState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedToEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CompletionToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTokenUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowStateId");

                    b.HasIndex("WorkflowTaskId");

                    b.ToTable("WorkflowTaskStates", (string)null);
                });

            modelBuilder.Entity("StackFlow.Domain.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Workspace"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Global"
                        });
                });

            modelBuilder.Entity("StackFlow.Domain.Models.User", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.Workspace", "Workspace")
                        .WithMany("Users")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.Workflow", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.Workspace", "Workspace")
                        .WithMany("Workflows")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowAudit", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.WorkflowState", "WorkflowState")
                        .WithMany("Audits")
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowState");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowState", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.Workflow", "Workflow")
                        .WithMany("States")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StackFlow.Domain.Models.Workspace", "Workspace")
                        .WithMany("WorkflowStates")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTask", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.WorkflowTask", "ParentTask")
                        .WithMany("ChildTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StackFlow.Domain.Models.Workflow", "Workflow")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTask");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTaskAudit", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.WorkflowTaskState", "WorkflowTaskState")
                        .WithMany("Audits")
                        .HasForeignKey("WorkflowTaskStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowTaskState");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTaskState", b =>
                {
                    b.HasOne("StackFlow.Domain.Models.WorkflowState", "WorkflowState")
                        .WithMany("TaskStates")
                        .HasForeignKey("WorkflowStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StackFlow.Domain.Models.WorkflowTask", "WorkflowTask")
                        .WithMany("States")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowState");

                    b.Navigation("WorkflowTask");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.Workflow", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowState", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("TaskStates");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTask", b =>
                {
                    b.Navigation("ChildTasks");

                    b.Navigation("States");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.WorkflowTaskState", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("StackFlow.Domain.Models.Workspace", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkflowStates");

                    b.Navigation("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
